<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>VehicleServiceApi</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../postman/sdks/Collections SDKs/Vehicle Service Collection/csharp/VehicleServiceCollectionSdk/VehicleServiceCollectionSdk.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
  </ItemGroup>
</Project>
