/**
 * This code was autogenerated from a Postman source
 */
const http = require('http');
const PORT = process.env.PORT || 4500;

const server = http.createServer((req, res) => {
  const url = new URL(req.url || '', 'http://localhost');
  const pathname = url.pathname;

  // @endpoint POST /vehicles
  if (req.method === 'POST' && pathname === '/vehicles') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "409 - Vehicle already exists" — when x-mock-response-code: 409
    if (requestedStatusCode === '409') {
      res.writeHead(409, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"Vehicle with VIN JN8AZ2KR1AT169594 already exists. Existing vehicle ID: 2"}));
    }

    // "400 - Missing required attribute" — when x-mock-response-code: 400
    if (requestedStatusCode === '400') {
      res.writeHead(400, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"Request body missing required attribute: vin"}));
    }

    // "500 - Unexpected error" — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"An unexpected error occurred."}));
    }

    // "201 - Success" — default
    res.writeHead(201, {"Content-Type":"application/json"});
    return res.end("{\n  \"id\": 1,\n  \"nickName\": \"The Lisa Marie\",\n  \"vin\": \"4M2DV11W4RDJ53329\",\n  \"make\": \"Mercury\",\n  \"model\": \"Villager\",\n  \"year\": \"1994\",\n  \"miles\": \"159,864\"\n}");
  }

  // @endpoint GET /vehicles/:id
  if (req.method === 'GET' && /^\/vehicles\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "404 - Not found" — when x-mock-response-code: 404
    if (requestedStatusCode === '404') {
      res.writeHead(404, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"Vehicle with id: 0 not found."}));
    }

    // "500 - Unexpected error" — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"An unexpected error occurred."}));
    }

    // "200 - Success" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":1,"nickName":"The Lisa Marie","vin":"4M2DV11W4RDJ53329","make":"Mercury","model":"Villager","year":"1994","miles":159864}));
  }

  // @endpoint PATCH /vehicles/:id
  if (req.method === 'PATCH' && /^\/vehicles\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "400 - Bad request body" — when x-mock-response-code: 400
    if (requestedStatusCode === '400') {
      res.writeHead(400, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"Bad request body."}));
    }

    // "500 - Unexpected error" — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"An unexpected error occurred."}));
    }

    // "200 - Success" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"id":1,"nickName":"The Lisa Marie","vin":"4M2DV11W4RDJ53329","make":"Mercury","model":"Villager","year":"1994","miles":159999}));
  }

  // @endpoint DELETE /vehicles/:id
  if (req.method === 'DELETE' && /^\/vehicles\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "500 - Unexpected error" — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"An unexpected error occurred."}));
    }

    // "204 - Success" — default
    res.writeHead(204, {"Content-Type":"text/plain"});
    return res.end("");
  }

  // @endpoint PUT /vehicles/:id
  if (req.method === 'PUT' && /^\/vehicles\/([^/]+)$/.test(pathname)) {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "Failure" — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"this is bad request"}));
    }

    // "Success" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify({"message":"this is good request"}));
  }

  // @endpoint GET /vehicles
  if (req.method === 'GET' && pathname === '/vehicles') {
    const requestedStatusCode = req.headers['x-mock-response-code'];

    // "500 - Unexpected error" — when x-mock-response-code: 500
    if (requestedStatusCode === '500') {
      res.writeHead(500, {"Content-Type":"application/json"});
      return res.end(JSON.stringify({"message":"An unexpected error occurred."}));
    }

    // "200 - Success" — default
    res.writeHead(200, {"Content-Type":"application/json"});
    return res.end(JSON.stringify([{"id":5313,"nickName":"string","vin":"string","make":"string","model":"string","year":"string","miles":6930},{"id":3319,"nickName":"string","vin":"string","make":"string","model":"string","year":"string","miles":1029}]));
  }

  res.writeHead(404, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({ error: 'Endpoint not defined' }));
});

server.listen(PORT);
